# **Part 3: Combining DataFrames, Text & Date Methods in Pandas**

### **Dataset Introduction**

In this project, we will work with the Palmer Penguins dataset, which contains measurements of penguins observed on islands near Antarctica.

Please download the dataset [penguins.csv](https://drive.google.com/file/d/1dv8A8v_sdf29p1At40S7KBslJPmBA3e9/view?usp=sharing) or from canvas.

### **Dataset Description**

Each row represents a penguin, and columns include:

- species – Penguin species
- island – Island where the penguin was found
- bill_length_mm – Bill length (mm)
- bill_depth_mm – Bill depth (mm)
- flipper_length_mm – Flipper length (mm)
- body_mass_g – Body mass (grams)
- sex – Sex of the penguin

Some values are missing, which makes this dataset ideal for practicing missing data handling.

### **Load the Dataset**

In [27]:
import pandas as pd

penguins = pd.read_csv('penguins.csv')
display(penguins.head())

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE

### **Part 1 — Basic Pandas Commands**

Q1. Display the dataset information.

In [35]:
penguins.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                334 non-null    object
 7   species_lower      344 non-null    object
dtypes: float64(4), object(4)
memory usage: 21.6+ KB

In [ ]:
# DO NOT RUN THIS

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                334 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

Q2. Display the number of unique species and unique islands.

In [3]:
print('unique species:', penguins['species'].nunique())

unique species: 3

In [4]:
print('unique islands:', penguins['island'].nunique())

unique islands: 3

In [ ]:
# DO NOT RUN THIS

3

In [ ]:
# DO NOT RUN THIS

3

### **Part 2 — GroupBy Basics**

Q3. Compute the average body mass for each species.

In [5]:
display(penguins.groupby('species')['body_mass_g'].mean())

species
Adelie       3700.662252
Chinstrap    3733.088235
Gentoo       5076.016260
Name: body_mass_g, dtype: float64

In [ ]:
# DO NOT RUN THIS

species
Adelie       3700.662252
Chinstrap    3733.088235
Gentoo       5076.016260
Name: body_mass_g, dtype: float64

Q4. Compute the average flipper length for each island.

In [6]:
display(penguins.groupby('island')['flipper_length_mm'].mean())

island
Biscoe       209.706587
Dream        193.072581
Torgersen    191.196078
Name: flipper_length_mm, dtype: float64

In [ ]:
# DO NOT RUN THIS

island
Biscoe       209.706587
Dream        193.072581
Torgersen    191.196078
Name: flipper_length_mm, dtype: float64

Q5. For each species, find the minimum, maximum, and mean of bill_length_mm.

In [7]:
display(penguins.groupby('species')['bill_length_mm'].agg(['min', 'max', 'mean']))

            min   max       mean
species
Adelie     32.1  46.0  38.791391
Chinstrap  40.9  58.0  48.833824
Gentoo     40.9  59.6  47.504878

In [ ]:
# DO NOT RUN THIS

            min   max       mean
species
Adelie     32.1  46.0  38.791391
Chinstrap  40.9  58.0  48.833824
Gentoo     40.9  59.6  47.504878

Q6. For each species–island combination, find the number of non-missing body mass measurements.

In [8]:
display(penguins.groupby(['species', 'island'])['body_mass_g'].count())

species    island
Adelie     Biscoe        44
           Dream         56
           Torgersen     51
Chinstrap  Dream         68
Gentoo     Biscoe       123
Name: body_mass_g, dtype: int64

In [ ]:
# DO NOT RUN THIS

species    island
Adelie     Biscoe        44
           Dream         56
           Torgersen     51
Chinstrap  Dream         68
Gentoo     Biscoe       123
Name: body_mass_g, dtype: int64

Q7. Identify the species with the largest average body mass.

In [9]:
average_mass = penguins.groupby('species')['body_mass_g'].mean()
print('largest average body mass:', average_mass.idxmax())

largest average body mass: Gentoo

In [ ]:
# DO NOT RUN THIS

'Gentoo'

Q8. Sort islands by descending average flipper length.

In [10]:
display(penguins.groupby('island')['flipper_length_mm'].mean().sort_values(ascending=False))

island
Biscoe       209.706587
Dream        193.072581
Torgersen    191.196078
Name: flipper_length_mm, dtype: float64

In [ ]:
# DO NOT RUN THIS

island
Biscoe       209.706587
Dream        193.072581
Torgersen    191.196078
Name: flipper_length_mm, dtype: float64

Q9.Find species–island groups with at least 20 penguins.

In [11]:
group_sizes = penguins.groupby(['species', 'island']).size()
display(group_sizes[group_sizes >= 20])
at_least_twenty = penguins.groupby(['species', 'island']).filter(lambda group: len(group) >= 20)
display(at_least_twenty)

species    island
Adelie     Biscoe        44
           Dream         56
           Torgersen     52
Chinstrap  Dream         68
Gentoo     Biscoe       124
dtype: int64

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [ ]:
# DO NOT RUN THIS

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

Q10. For each species, compute:

- average body mass
- average flipper length

In [12]:
display(penguins.groupby('species')[['body_mass_g', 'flipper_length_mm']].mean())

           body_mass_g  flipper_length_mm
species
Adelie     3700.662252         189.953642
Chinstrap  3733.088235         195.823529
Gentoo     5076.016260         217.186992

In [ ]:
# DO NOT RUN THIS

           body_mass_g  flipper_length_mm
species
Adelie     3700.662252         189.953642
Chinstrap  3733.088235         195.823529
Gentoo     5076.016260         217.186992

Q11. For each island, compute:

- count of penguins
- mean body mass
- standard deviation of body mass

In [13]:
island_summary = penguins.groupby('island')['body_mass_g'].agg(['size', 'count', 'mean', 'std'])
display(island_summary)
print('size counts all penguins; count includes only known body masses.')

           size  count         mean         std
island
Biscoe      168    167  4716.017964  782.855743
Dream       124    124  3712.903226  416.644112
Torgersen    52     51  3706.372549  445.107940

size counts all penguins; count includes only known body masses.

In [ ]:
# DO NOT RUN THIS

           count         mean         std
island
Biscoe       167  4716.017964  782.855743
Dream        124  3712.903226  416.644112
Torgersen     51  3706.372549  445.107940

### **Part 3 — Combining DataFrames + GroupBy**

Q12. Create the following penguin_regions dataframe and merge with penguins.



```
{
    'island': ['Biscoe', 'Dream', 'Torgersen'],
    'region': ['Antarctica', 'Antarctica', 'Antarctica']
}
```

In [28]:
penguin_regions = pd.DataFrame({'island': ['Biscoe', 'Dream', 'Torgersen'], 'region': ['Antarctica', 'Antarctica', 'Antarctica']})
penguins_with_region = penguins.merge(penguin_regions, on='island', how='left')
display(penguins_with_region.head())
print('rows after merge:', len(penguins_with_region))

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,region
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE,Antarctica
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE,Antarctica
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE,Antarctica
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,Antarctica
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE,Antarctica

rows after merge: 344

Q13. Compute the average body mass per region.

In [33]:
display(penguins_with_region.groupby('region')['body_mass_g'].mean())

region
Antarctica    4201.754386
Name: body_mass_g, dtype: float64

In [ ]:
# DO NOT RUN THIS

region
Antarctica    4201.754386
Name: body_mass_g, dtype: float64

Q14.Compute the average body_mass_g grouped by species, and then compute the overall average body_mass_g without grouping.

- Why are the species-level averages different from the overall average?
- What does this tell you about how groupby() changes the interpretation of results?

In [16]:
species_mean_mass = penguins.groupby('species')['body_mass_g'].mean()
overall_mean_mass = penguins['body_mass_g'].mean()
display(species_mean_mass)
print('overall mean body mass:', overall_mean_mass)

species
Adelie       3700.662252
Chinstrap    3733.088235
Gentoo       5076.016260
Name: body_mass_g, dtype: float64

overall mean body mass: 4201.754385964912

In [ ]:
# DO NOT RUN THIS

np.float64(4201.754385964912)

In [ ]:
# DO NOT RUN THIS

species
Adelie       3700.662252
Chinstrap    3733.088235
Gentoo       5076.016260
Name: body_mass_g, dtype: float64

Your Explanation:

the species averages differ because each species has its own body masses. the overall mean uses all 342 penguins with a recorded body mass, so species with more measurements have more weight. groupby changes which rows are averaged together.

### **Part 4 — GroupBy with Text Methods**

Q15. Create species_lower with lowercase species names.

In [30]:
penguins['species_lower'] = penguins['species'].str.lower()
display(penguins.head())

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_lower
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE,adelie
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE,adelie
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE,adelie
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,adelie
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE,adelie

In [ ]:
# DO NOT RUN THIS

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_lower
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE,adelie
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE,adelie
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE,adelie
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,adelie
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE,adelie

Q16. After creating the species_lower column, you want to verify that converting text to lowercase did not change the number of observations for each species.

Compute the number of penguins for each value in species_lower.

In [31]:
display(penguins['species_lower'].value_counts())

species_lower
adelie       152
gentoo       124
chinstrap     68
Name: count, dtype: int64

In [ ]:
# DO NOT RUN THIS

species_lower
adelie       152
gentoo       124
chinstrap     68
Name: count, dtype: int64

Q17. Create penguin_observations, with the following data.

observation_date': '2019-01-15', '2019-02-20', '2020-01-05', '2020-03-18'

In [24]:
penguin_observations = pd.DataFrame({'penguin_id': [1, 2, 3, 4], 'observation_date': ['2019-01-15', '2019-02-20', '2020-01-05', '2020-03-18']})
display(penguin_observations)

   penguin_id observation_date
0           1       2019-01-15
1           2       2019-02-20
2           3       2020-01-05
3           4       2020-03-18

In [ ]:
# DO NOT RUN THIS

   penguin_id observation_date
0           1       2019-01-15
1           2       2019-02-20
2           3       2020-01-05
3           4       2020-03-18

Q19. Convert observation_date to datetime and extract year.

In [25]:
penguin_observations['observation_date'] = pd.to_datetime(penguin_observations['observation_date'])
penguin_observations['year'] = penguin_observations['observation_date'].dt.year
display(penguin_observations)

   penguin_id observation_date  year
0           1       2019-01-15  2019
1           2       2019-02-20  2019
2           3       2020-01-05  2020
3           4       2020-03-18  2020

In [ ]:
# DO NOT RUN THIS

   penguin_id observation_date  year
0           1       2019-01-15  2019
1           2       2019-02-20  2019
2           3       2020-01-05  2020
3           4       2020-03-18  2020

Q20. Merge with original penguins dataframe and show the head.

In [32]:
# one-based IDs match the four example observations above
penguins_with_ids = penguins.copy()
penguins_with_ids['penguin_id'] = penguins_with_ids.index + 1
penguins_with_dates = penguins_with_ids.merge(penguin_observations, on='penguin_id', how='left')
display(penguins_with_dates.head())
print('rows after merge:', len(penguins_with_dates))
print('rows with example dates:', penguins_with_dates['observation_date'].notna().sum())

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_lower,penguin_id,observation_date,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE,adelie,1,2019-01-15,2019.0
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE,adelie,2,2019-02-20,2019.0
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE,adelie,3,2020-01-05,2020.0
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,adelie,4,2020-03-18,2020.0
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE,adelie,5,NaT,NaN

rows after merge: 344
rows with example dates: 4

In [ ]:
# DO NOT RUN THIS

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_lower,penguin_id,observation_date,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE,adelie,0,2019-01-15,2019.0
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE,adelie,1,2019-02-20,2019.0
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE,adelie,2,2020-01-05,2020.0
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,adelie,3,2020-03-18,2020.0
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE,adelie,4,NaT,NaN